---
- name: Configure | php5-fpm | expose_php
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php.ini
    regexp: '^;* *expose_php = '
    line: 'expose_php = Off'
  notify: Reload Service | php5-fpm
  when: php_hide_version
  tags:
    - configuration
    - precise-configuration
    - improves-security
    - php

- name: Configure | php5-fpm | listen on unix socket
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php-fpm.conf
    regexp: '^;* *listen = '
    line: "listen = {{ php_fpm_socket_path }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - improves-security
    - unix-socket
    - php
