---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - "{% if php_fpm %}php5-fpm{% else %}php5-cli{% endif %}"
  tags:
    - software-installation
    - using-apt

- name: Service Stopped | php5-fpm
  service:
    state: stopped
    name: php5-fpm
  when: php_fpm
  tags:
    - disruptive
