---
- name: Import Signing Key | ~ondrej
  apt_key:
    state: present
    keyserver: 'hkp://keyserver.ubuntu.com:80'
    id: '0x4f4ea0aae5267a6c'

- name: Import Repository | ~ondrej/php5
  apt_repository:
    state: present
    repo: 'deb http://ppa.launchpad.net/ondrej/php5/ubuntu trusty main'
  notify: Update Package Cache

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - php5-fpm
  tags:
    - software-installation
    - using-apt

- name: Service Stopped | php5-fpm
  service:
    state: stopped
    name: php5-fpm
  tags:
    - disruptive
