---
- name: Install Packages | apt
  apt:
    state: latest
    pkg: "{{ item }}"
  with_items:
    - php5-fpm
  tags:
    - software-installation
    - using-apt

- name: Service Stopped | php5-fpm
  service:
    state: stopped
    name: php5-fpm
  tags:
    - disruptive
