---
- name: Upload Config | beaver | php5-fpm
  template:
    src: etc/beaver/conf.d/php5-fpm
    dest: /etc/beaver/conf.d/php5-fpm
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - php
