---
- name: "Directory Exists | {{ php_log_root }}"
  file:
    state: directory
    path: "{{ php_log_root }}"
    owner: "{{ php_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - php

- name: Configure | php5-fpm | php-fpm.conf
  ini_file:
    dest: /etc/php5/fpm/php-fpm.conf
    section: global
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'error_log',               value: "{{ php_fpm_log_path }}" }
    - { option: 'request_slowlog_timeout', value: "{{ php_slow_threshold }}" }
    - { option: 'slowlog',                 value: "{{ php_slow_log_path }}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - ini-configuration
    - logging
    - php

- name: Configure | php5-fpm | php-fpm.conf
  ini_file:
    dest: /etc/php5/fpm/php.ini
    section: PHP
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { option: 'error_log',               value: "{{ php_error_log_path }}" }
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - ini-configuration
    - logging
    - php

- name: Upload Config | beaver | php5-fpm
  template:
    src: etc/beaver/conf.d/php5-fpm
    dest: /etc/beaver/conf.d/php5-fpm
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - php
