---
- name: "Directory Exists | {{ php_log_root }}"
  file:
    state: directory
    path: "{{ php_log_root }}"
    owner: "{{ php_user }}"
    group: wcadmin
    mode: 0775
  tags:
    - directory-structure
    - logging
    - php

- name: Configure | php5-fpm | fpm logfile
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php-fpm.conf
    regexp: '^;* *error_log = '
    line: "error_log = {{ php_fpm_log_path }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - logging
    - php

- name: Configure | php5-fpm | php logfile
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php.ini
    regexp: '^;* *error_log = '
    line: "error_log = {{ php_error_log_path }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - logging
    - php

- name: Configure | php5-fpm | slow logfile
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php-fpm.conf
    regexp: '^;* *slowlog = '
    line: "slowlog = {{ php_slow_log_path }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - logging
    - php

- name: Configure | php5-fpm | slow log threshold
  lineinfile:
    state: present
    dest: /etc/php5/fpm/php-fpm.conf
    regexp: '^;* *request_slowlog_timeout = '
    line: "request_slowlog_timeout = {{ php_slow_threshold }}"
  notify: Reload Service | php5-fpm
  tags:
    - configuration
    - precise-configuration
    - logging
    - php

- name: Upload Config | beaver | php5-fpm
  template:
    src: etc/beaver/conf.d/php5-fpm
    dest: /etc/beaver/conf.d/php5-fpm
  tags:
    - configuration
    - template-configuration
    - logging
    - using-beaver
    - php
