---
- name: Upload Config | monit | php5-fpm
  template:
    src: etc/monit/conf.d/php5-fpm
    dest: /etc/monit/conf.d/php5-fpm
  notify: Reload Service | monit

- name: Trigger All Callbacks
  meta: flush_handlers

- name: Confirm Monitoring | php5-fpm
  monit:
    state: present
    name: php5-fpm
