---
- name: Directories Exists
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ php_user }}"
    group: wcadmin
    mode: 0775
  with_items:
    - php_log_root
    - php_runtime_root
  tags:
    - filesystem-layout
    - php
